### ISSUE TITLE
Use json_serializable for generating from/to JSON

### ISSUE THREAD

**Issue by SuperPenguin** [Riktam-Santra/mangadex_library#1]
Writing `fromJson` manually is fine but it will hard to maintaining parsing from/to json.

For example: there is typo here https://github.com/Riktam-Santra/mangadexForDart/blob/bbcdffee75241cf3b03848dd6cbcf022186e6df1/mangadex_library/lib/search/Search.dart#L41

If you need help, I can do PR.

**Comment by Riktam-Santra** [comment]
Yeah didn't see that one, thanks. I'm thinking of using automated websites for generating classes to parse the JSON from now on, manual creation really does need a lot of attention to typos. Anyways, I fixed it now.
