### ISSUE TITLE
Refactor searchResponse Method

### ISSUE THREAD

**Issue by Mtlayones** [Riktam-Santra/mangadex_library#2]
1.  IncludedTags = IncludedTags + '&includedTages[]=$element'; -> IncludedTags = IncludedTags + '&includedTags[]=$element'; 
2. var Order = order != null
      ? '&order[${order.entries.first}]=${order[order.entries.first]}'
      : '&order[recentlyUpdated]=desc'; -> recentlyUpdated is a validation error for the order query

**Comment by Riktam-Santra** [comment]
Thanks for reporting this, almost forgot to test the searchResponse function. It's now fixed in 1.3.10
